# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/typescript' # Location of package file
    schedule:
      interval: 'weekly'
    # Group related deps into single PR
    groups:
      # Semantic versioning groups (catch-all for ungrouped dependencies)
      patch-updates:
        update-types:
          - 'patch'
      minor-updates:
        update-types:
          - 'minor'
      # Specific package groups (these take precedence over semantic groups)
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      capacitor:
        patterns:
          - '@capacitor/*'
      redux:
        patterns:
          - 'redux'
          - 'redux-*'
          - 'react-redux'
          - 'reselect'
          - 'redux-mock-store'
          - '@types/react-redux'
          - '@types/redux-mock-store'
      sinon-fake-timers:
        patterns:
          - '@sinonjs/fake-timers'
          - '@types/sinonjs__fake-timers'
 